name: Reusable - Publish Release to Maven Central

on:
  workflow_call:
    inputs:
      java-version:
        default: '21'
        type: string
      java-distribution:
        default: 'temurin'
        type: string
      namespace:
        default: 'org.eclipse.keypop'
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: ${{ inputs.java-version }}
      JAVA_DISTRIBUTION: ${{ inputs.java-distribution }}
      NAMESPACE: ${{ inputs.namespace }}
      SONATYPE_DEPLOY_URL: https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Extract project name and version
        id: metadata
        run: |
          PROJECT_NAME=$(./gradlew -q properties | grep "^rootProject:" | awk '{print $2}')
          PROJECT_VERSION=$(./gradlew -q properties | grep "^version:" | awk '{print $2}')
          echo "project-name=$PROJECT_NAME" >> $GITHUB_OUTPUT
          echo "project-version=$PROJECT_VERSION" >> $GITHUB_OUTPUT

      - name: Check version
        run: |
          EXPECTED_PROJECT_VERSION="${{ github.event.release.tag_name }}-SNAPSHOT"
          ACTUAL_PROJECT_VERSION="${{ steps.metadata.outputs.project-version }}"

          echo "Expected project version: $EXPECTED_PROJECT_VERSION"
          echo "Actual project version from gradle.properties: $ACTUAL_PROJECT_VERSION"

          if [ "$EXPECTED_PROJECT_VERSION" != "$ACTUAL_PROJECT_VERSION" ]; then
            echo "::error::Mismatch between release tag and project version"
            exit 1
          fi

      - name: Retrieve fingerprint of the signing subkey
        id: fingerprint
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" > private.key
          gpg --batch --import private.key
          fingerprint=$(gpg --list-keys --with-subkey-fingerprint | awk '/^sub/ {getline; print $1}')
          echo "fingerprint=$fingerprint" >> $GITHUB_OUTPUT

      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          fingerprint: ${{ steps.fingerprint.outputs.fingerprint }}

      - name: Build and publish release
        env:
          ORG_GRADLE_PROJECT_sonatypeURL: ${{ env.SONATYPE_DEPLOY_URL }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}
          ORG_GRADLE_PROJECT_releaseTag: ${{ github.event.release.tag_name }}
        run: |
          echo "Building and publishing release package..."
          ./gradlew build publish --info --stacktrace

      - name: Trigger automatic upload to Maven Central
        run: |
          curl -X POST \
            -H "Authorization: Bearer $(echo -n '${{ secrets.CENTRAL_SONATYPE_TOKEN_USERNAME }}:${{ secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD }}' | base64)" \
            -H "Content-Type: application/json" \
            https://ossrh-staging-api.central.sonatype.com/manual/upload/defaultRepository/${{ env.NAMESPACE }}?publishing_type=automatic

      - name: Upload artifacts to Eclipse server
        uses: eclipse-keypop/keypop-actions/actions/deploy-to-eclipse@deploy-to-eclipse-v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}
          version-type: releases

      - name: Update documentation branch
        uses: ./.github/actions/update-doc-branch@update-doc-branch-v1
        with:
          project-name: ${{ steps.metadata.outputs.project-name }}
          keypop-version: ${{ steps.metadata.outputs.project-version }}
          deploy-type: release
